travis:
  secure:
    BINSTAR_TOKEN: YOZVDG6Ucw/QGQ7ovVkeMJfF4CL01gx2b2BWiYcIFGdxi+nkX7ZZk/OhDv9QJiZB1S/koCQJ+EMjkzN+l2mFiJgT+Qv+dmWFx09TnEX8RAdMOCRiEHgjmkrgqYlyUPOaA+W7A0FKOKZ2t0HSg1fHuYDB1Vb4grydbl7AJzYmxGuRWTddlRgzHIMIGpeI+bHTjK3ZO5RTM7qateGCJdYwshvti2WANSyEbeUm7vXP2G1L0XdB6iGhR+BCl4J+b7CPf1G5szIzOx2IFY2r5LJ3A7xxEIyLfAtDChjUcOwcO6TdInn7WXAGvPZ4lvmYQOGTZq3rFA6wVtXs3+h0kNflrMU9w5HDRfdaeM0TK+Cz2BsGJWdCXyfBRZouieara7HA9ndkUIjGuie6Zj54njEvyDQDJNXaFrb9B5/bLIu9GRNkNDmm6Z/k6jRGJD0qttKMHxCtM56CenoRZf6TOurvnQZRdFHUTiP9QA5Wi2NEi3VPLXW3lnXr8wBTCfyYGnGPbywENAb4uVe0KnJiR6NhM/xsySoF6U4RwXi2/c6+BwgE7mYgSx/b2T3KswoBDLt5QtE3n+yCHPnwP0xs2yOmv3doFXv/BEe4ay94Zxy4ATS9O2jiUmL6UQ6pdmAbPLUd0zI2ueUiHYJo25FYKiuPIyR2yOfKOdzWNaI5/qCCZpU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
