appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aI+vfi263tMg89luIFaYyjTUpJSIDxK4nDLfpzYN/eD6Gzh498rpKkKH8dGXoNg0MgwaH8YDwU5o8rPTBimEhdYaHU0auvz58scy+iryAOMaUd2BEtCEP4iN+s4fLUw7E4iRjg1a87q96F8SpZwh8AS0WorvK6UxCNr0Emx4rvi7YgCPMXtUxcg+8PLGna1RRdJsd+jfvMcBO/Qb5sjBJzbfrY7xjaWh6SxTVFPn34OMEURBpqLtG/RDLNqRzWrKhMX456qBwGZUAm7OYa/pg3P9h488vaHNkQqRqzToG+awoYTy5xPOplAl3m6FtPEFLN/dOYlr4kh7hjZ+6z9KjYvA6C6dq5qx90XLv86MiJGjOtw/m6lqMt0PYj6C6WEuU3PAQ5pOPj0DyGb1GHtPMSXi9A25eGW9EM/7oGyBBmT9NZFqo2CveDh7H7nkBzOIrKkHta4n2JLRhFE5w0799UB6/mAoJTmiB9wWB+OZxq9OJDyFsJxO6CvwR/Gg/CspzzevFWQe3wwqEH2fI4vZbfg5xi7z7e2iPTBenP/0GDzI+p1UOZAUduS8C3pnODGFMp6Ep1Syx3H0ejfl3Tl6//IulHq2m2A/my7JGwiMWzOR29V/Xua1Ec/V8iOwg9Rd8tXJPyfkdYXwG2g+YWv3GNFO8PzqNw4ZIAkokycB0uM=}
